name = playerfactions
title = Player Factions
description = Allows player created factions. It becomes very powerful when combined with other mods.
min_minetest_version = 5.10.0
optional_depends = mtt
